import pymongo
client = pymongo.MongoClient("mongodb+srv://y4s1assignments:5bdk2OiVOb4DIKVi@cluster0.m94hxjb.mongodb.net/?retryWrites=true&w=majority")
db = client["Dog_Care_Research"]
collection = db["Breeds"]

# Check if the connection to the MongoDB instance is successful
try:
    # The ismaster command is used to check the connection
    client.admin.command('ismaster')
    print("Connection successful!")
except pymongo.errors.ServerSelectionTimeoutError as error:
    print(f"Connection failed: {error}")

# Insert a document into the collection
records = [
    {"Name": "Chihuahua", "size": 1, "MinWeight": 2, "MaxWeight": 7, "AverageActivity": "low"}, 
    {"Name": "Japanese Spaniel", "size": 1, "MinWeight": 3, "MaxWeight": 15, "AverageActivity": "medium"}, 
    {"Name": "Maltese", "size": 1, "MinWeight": 3.5, "MaxWeight": 7, "AverageActivity": "high"},
    {"Name": "Pekinese", "size": 1, "MinWeight": 8, "MaxWeight": 14, "AverageActivity": "low"},
    {"Name": "Shih Tzu", "size": 1, "MinWeight": 9, "MaxWeight": 16, "AverageActivity": "medium"},
    {"Name": "Blenheim Spaniel", "size": 1, "MinWeight": 8, "MaxWeight": 14, "AverageActivity": "medium"},
    {"Name": "Papillon", "size": 1, "MinWeight": 8, "MaxWeight": 10, "AverageActivity": "high"},
    {"Name": "Toy terrier", "size": 1, "MinWeight": 6, "MaxWeight": 8, "AverageActivity": "high"},
    {"Name": "Rhodesian ridgeback", "size": 4, "MinWeight": 70, "MaxWeight": 85, "AverageActivity": "high"},
    {"Name": "Afghan hound", "size": 3, "MinWeight": 44, "MaxWeight": 60, "AverageActivity": "high"},
    {"Name": "Basset", "size": 3, "MinWeight": 44, "MaxWeight": 74, "AverageActivity": "medium"},
    {"Name": "Beagle", "size": 2, "MinWeight": 20, "MaxWeight": 25, "AverageActivity": "high"},
    {"Name": "Bloodhound", "size": 5, "MinWeight": 72, "MaxWeight": 110, "AverageActivity": "high"},
    {"Name": "Bluetick", "size": 4, "MinWeight": 55, "MaxWeight": 80, "AverageActivity": "high"},
    {"Name": "Black&Tan coonhound", "size": 4, "MinWeight": 64, "MaxWeight": 75, "AverageActivity": "high"},
    {"Name": "Walker hound", "size": 3, "MinWeight": 44, "MaxWeight": 64, "AverageActivity": "high"},
    {"Name": "English foxhound", "size": 4, "MinWeight": 64, "MaxWeight": 75, "AverageActivity": "high"},
    {"Name": "Redbone", "size": 3, "MinWeight": 44, "MaxWeight": 70, "AverageActivity": "high"},
    {"Name": "Borzoi", "size": 4, "MinWeight": 55, "MaxWeight": 103, "AverageActivity": "high"},
    {"Name": "Irish wolfhound", "size": 5, "MinWeight": 105, "MaxWeight": 155, "AverageActivity": "low"},
    {"Name": "Italian greyhound", "size": 1, "MinWeight": 8, "MaxWeight": 11, "AverageActivity": "medium"},
    {"Name": "Whippet", "size": 2, "MinWeight": 15, "MaxWeight": 42, "AverageActivity": "high"},
    {"Name": "Ibizan hound", "size": 3, "MinWeight": 44, "MaxWeight": 66, "AverageActivity": "high"},
    {"Name": "Norwegian elkhound", "size": 3, "MinWeight": 48.5, "MaxWeight": 55, "AverageActivity": "high"},
    {"Name": "Otter hound", "size": 5, "MinWeight": 64, "MaxWeight": 110, "AverageActivity": "high"},
    {"Name": "Saluki", "size": 3, "MinWeight": 40, "MaxWeight": 60, "AverageActivity": "high"},
    {"Name": "Scottish deerhound", "size": 5, "MinWeight": 77, "MaxWeight": 110, "AverageActivity": "low"},
    {"Name": "Weimaraner", "size": 4, "MinWeight": 55, "MaxWeight": 81, "AverageActivity": "high"},
    {"Name": "Staffordshire bull terrier", "size": 2, "MinWeight": 24, "MaxWeight": 37, "AverageActivity": "high"},
    {"Name": "American staffordshire terrier", "size": 3, "MinWeight": 40, "MaxWeight": 70, "AverageActivity": "high"},
    {"Name": "Bedlington terrier", "size": 2, "MinWeight": 17, "MaxWeight": 22, "AverageActivity": "medium"},
    {"Name": "Border terrier", "size": 1, "MinWeight": 12.5, "MaxWeight": 15.4, "AverageActivity": "high"},
    {"Name": "Kerry Blue terrier", "size": 2, "MinWeight": 33, "MaxWeight": 40, "AverageActivity": "high"},
    {"Name": "Irish terrier", "size": 2, "MinWeight": 24, "MaxWeight": 26.5, "AverageActivity": "high"},
    {"Name": "Norfolk terrier", "size": 1, "MinWeight": 11, "MaxWeight": 12, "AverageActivity": "high"},
    {"Name": "Norwich terrier", "size": 1, "MinWeight": 11, "MaxWeight": 12, "AverageActivity": "high"},
    {"Name": "Yorkshire terrier", "size": 1, "MinWeight": 6, "MaxWeight": 10, "AverageActivity": "high"},
    {"Name": "Wirehaired foxterrier", "size": 1, "MinWeight": 15, "MaxWeight": 19, "AverageActivity": "high"},
    {"Name": "Lakeland terrier", "size": 1, "MinWeight": 15.5, "MaxWeight": 17.5, "AverageActivity": "high"},
    {"Name": "Sealyham terrier", "size": 1, "MinWeight": 17.5, "MaxWeight": 20, "AverageActivity": "medium"},
    {"Name": "Airedale", "size": 3, "MinWeight": 40, "MaxWeight": 64, "AverageActivity": "high"},
    {"Name": "Cairn", "size": 1, "MinWeight": 13, "MaxWeight": 17.5, "AverageActivity": "high"},
    {"Name": "Australian terrier", "size": 1, "MinWeight": 12, "MaxWeight": 16, "AverageActivity": "high"},
    {"Name": "Dandie Dinmont", "size": 2, "MinWeight": 18, "MaxWeight": 24, "AverageActivity": "medium"},
    {"Name": "Boston bull", "size": 1, "MinWeight": 10, "MaxWeight": 24, "AverageActivity": "high"},
    {"Name": "Miniature schnauzer", "size": 1, "MinWeight": 10, "MaxWeight": 18, "AverageActivity": "medium"},
    {"Name": "Giant schnauzer", "size": 4, "MinWeight": 55, "MaxWeight": 105, "AverageActivity": "high"},
    {"Name": "Standard schnauzer", "size": 2, "MinWeight": 31, "MaxWeight": 44, "AverageActivity": "high"},
    {"Name": "Scotch terrier", "size": 2, "MinWeight": 17.5, "MaxWeight": 22, "AverageActivity": "high"},
    {"Name": "Tibetan terrier", "size": 2, "MinWeight": 17.5, "MaxWeight": 31, "AverageActivity": "high"},
    {"Name": "Silky terrier", "size": 1, "MinWeight": 8, "MaxWeight": 11, "AverageActivity": "high"},
    {"Name": "Softcoated wheatenterrier", "size": 2, "MinWeight": 31, "MaxWeight": 40, "AverageActivity": "high"},
    {"Name": "WestHighland whiteterrier", "size": 1, "MinWeight": 15, "MaxWeight": 20, "AverageActivity": "high"},
    {"Name": "Lhasa", "size": 1, "MinWeight": 12, "MaxWeight": 18, "AverageActivity": "medium"},
    {"Name": "Flatcoated retriever", "size": 4, "MinWeight": 55, "MaxWeight": 80, "AverageActivity": "high"},
    {"Name": "Curlycoated retriever", "size": 4, "MinWeight": 50, "MaxWeight": 90, "AverageActivity": "high"},
    {"Name": "Golden retriever", "size": 4, "MinWeight": 55, "MaxWeight": 75, "AverageActivity": "high"},
    {"Name": "Labrador retriever", "size": 4, "MinWeight": 55, "MaxWeight": 80, "AverageActivity": "low"},
    {"Name": "Chesapeake Bayretriever", "size": 1, "MinWeight": 55, "MaxWeight": 80, "AverageActivity": "high"},
    {"Name": "German shortHaired pointer", "size": 3, "MinWeight": 44, "MaxWeight": 70, "AverageActivity": "high"},
    {"Name": "Vizsla", "size": 3, "MinWeight": 40, "MaxWeight": 64, "AverageActivity": "high"},
    {"Name": "English setter", "size": 4, "MinWeight": 45, "MaxWeight": 80, "AverageActivity": "medium"},
    {"Name": "Irish setter", "size": 4, "MinWeight": 55, "MaxWeight": 75, "AverageActivity": "high"},
    {"Name": "Gordon setter", "size": 4, "MinWeight": 44, "MaxWeight": 80, "AverageActivity": "high"},
    {"Name": "Brittany spaniel", "size": 2, "MinWeight": 35, "MaxWeight": 42, "AverageActivity": "high"},
    {"Name": "Clumber", "size": 4, "MinWeight": 55, "MaxWeight": 86, "AverageActivity": "low"},
    {"Name": "English springer wolfhound", "size": 3, "MinWeight": 40, "MaxWeight": 53, "AverageActivity": "medium"},
    {"Name": "Welsh springer spaniel", "size": 3, "MinWeight": 35, "MaxWeight": 55, "AverageActivity": "high"},
    {"Name": "Cocker spaniel", "size": 2, "MinWeight": 28.5, "MaxWeight": 31, "AverageActivity": "high"},
    {"Name": "Sussex spaniel", "size": 3, "MinWeight": 35, "MaxWeight": 44, "AverageActivity": "medium"},
    {"Name": "Irish waterspaniel", "size": 3, "MinWeight": 44, "MaxWeight": 66, "AverageActivity": "high"},
    {"Name": "Kuvasz", "size": 5, "MinWeight": 77, "MaxWeight": 115, "AverageActivity": "high"},
    {"Name": "Schipperke", "size": 1, "MinWeight": 6.5, "MaxWeight": 20, "AverageActivity": "high"},
    {"Name": "Groenendael", "size": 3, "MinWeight": 44, "MaxWeight": 66, "AverageActivity": "high"},
    {"Name": "Malinois", "size": 3, "MinWeight": 44, "MaxWeight": 66, "AverageActivity": "high"},
    {"Name": "Briard", "size": 4, "MinWeight": 55, "MaxWeight": 88, "AverageActivity": "high"},
    {"Name": "Kelpie", "size": 3, "MinWeight": 31, "MaxWeight": 46, "AverageActivity": "high"},
    {"Name": "Komondor", "size": 5, "MinWeight": 88, "MaxWeight": 132, "AverageActivity": "medium"},
    {"Name": "OldEnglish sheepdog", "size": 5, "MinWeight": 60, "MaxWeight": 99, "AverageActivity": "high"},
    {"Name": "Shetland sheepdog", "size": 1, "MinWeight": 16, "MaxWeight": 20, "AverageActivity": "high"},
    {"Name": "Collie", "size": 4, "MinWeight": 44, "MaxWeight": 75, "AverageActivity": "high"},
    {"Name": "Border collie", "size": 2, "MinWeight": 26.5, "MaxWeight": 44, "AverageActivity": "high"},
    {"Name": "Bouvier des Flandres", "size": 5, "MinWeight": 60, "MaxWeight": 119, "AverageActivity": "high"},
    {"Name": "Rottweiler", "size": 5, "MinWeight": 77, "MaxWeight": 132, "AverageActivity": "high"},
    {"Name": "German shepherd", "size": 4, "MinWeight": 48.5, "MaxWeight": 88, "AverageActivity": "high"},
    {"Name": "Doberman", "size": 5, "MinWeight": 70.5, "MaxWeight": 100, "AverageActivity": "high"},
    {"Name": "Miniature pinscher", "size": 1, "MinWeight": 8, "MaxWeight": 10.5, "AverageActivity": "high"},
    {"Name": "Greater SwissMountain", "size": 5, "MinWeight": 106, "MaxWeight": 143, "AverageActivity": "high"},
    {"Name": "Bernese mountain", "size": 5, "MinWeight": 80, "MaxWeight": 110, "AverageActivity": "medium"},
    {"Name": "Appenzeller", "size": 4, "MinWeight": 48.5, "MaxWeight": 70.5, "AverageActivity": "high"},
    {"Name": "EntleBucher", "size": 3, "MinWeight": 44, "MaxWeight": 66, "AverageActivity": "high"},
    {"Name": "Boxer", "size": 4, "MinWeight": 55, "MaxWeight": 70.5, "AverageActivity": "high"},
    {"Name": "Bull mastiff", "size": 5, "MinWeight": 99, "MaxWeight": 130, "AverageActivity": "high"},
    {"Name": "Tibetan mastiff", "size": 5, "MinWeight": 75, "MaxWeight": 150, "AverageActivity": "medium"},
    {"Name": "French bull", "size": 2, "MinWeight": 16, "MaxWeight": 28, "AverageActivity": "medium"},
    {"Name": "Great Dane", "size": 5, "MinWeight": 99, "MaxWeight": 198, "AverageActivity": "high"},
    {"Name": "Saint Bernard", "size": 5, "MinWeight": 120, "MaxWeight": 180, "AverageActivity": "medium"},
    {"Name": "Eskimo", "size": 2, "MinWeight": 18, "MaxWeight": 35, "AverageActivity": "high"},
    {"Name": "Malamute", "size": 4, "MinWeight": 75, "MaxWeight": 84, "AverageActivity": "high"},
    {"Name": "Siberian husky", "size": 3, "MinWeight": 35, "MaxWeight": 60, "AverageActivity": "high"},
    {"Name": "Affenpinscher", "size": 1, "MinWeight": 6, "MaxWeight": 13, "AverageActivity": "high"},
    {"Name": "Basenji", "size": 2, "MinWeight": 21, "MaxWeight": 24, "AverageActivity": "high"},
    {"Name": "Pug", "size": 1, "MinWeight": 14, "MaxWeight": 18, "AverageActivity": "low"},
    {"Name": "Leonberg", "size": 5, "MinWeight": 90, "MaxWeight": 170, "AverageActivity": "medium"},
    {"Name": "Newfoundland", "size": 5, "MinWeight": 121, "MaxWeight": 176, "AverageActivity": "high"},
    {"Name": "Great Pyrenees", "size": 5, "MinWeight": 86, "MaxWeight": 160, "AverageActivity": "high"},
    {"Name": "Samoyedr", "size": 3, "MinWeight": 35, "MaxWeight": 66, "AverageActivity": "high"},
    {"Name": "Pomeranian", "size": 1, "MinWeight": 4, "MaxWeight": 7.5, "AverageActivity": "medium"},
    {"Name": "Chow", "size": 3, "MinWeight": 44, "MaxWeight": 70, "AverageActivity": "medium"},
    {"Name": "Keeshond", "size": 2, "MinWeight": 30, "MaxWeight": 40, "AverageActivity": "high"},
    {"Name": "Brabancon griffon", "size": 1, "MinWeight": 5, "MaxWeight": 15, "AverageActivity": "high"},
    {"Name": "Pembroke", "size": 2, "MinWeight": 24, "MaxWeight": 26.5, "AverageActivity": "high"},
    {"Name": "Cardigan", "size": 2, "MinWeight": 24, "MaxWeight": 37, "AverageActivity": "medium"},
    {"Name": "Toy poodle", "size": 1, "MinWeight": 6, "MaxWeight": 10, "AverageActivity": "high"},
    {"Name": "Miniature poodle", "size": 1, "MinWeight": 10, "MaxWeight": 15, "AverageActivity": "high"},
    {"Name": "Standard poodle", "size": 3, "MinWeight": 45, "MaxWeight": 70, "AverageActivity": "high"},
    {"Name": "Mexican hairless", "size": 2, "MinWeight": 9, "MaxWeight": 55, "AverageActivity": "high"},
    {"Name": "Dingo", "size": 2, "MinWeight": 22, "MaxWeight": 33, "AverageActivity": "high"},
    {"Name": "Dhole", "size": 2, "MinWeight": 26.5, "MaxWeight": 44, "AverageActivity": "high"},
    {"Name": "African hunter", "size": 3, "MinWeight": 40, "MaxWeight": 56, "AverageActivity": "high"}
]
collection.insert_many(records)
print("Document inserted successfully!")